export const JWT_SECRET = {
  secret:
    "DO NOT USE THIS VALUE. INSTEAD, CREATE A COMPLEX SECRET AND KEEP IT SAFE OUTSIDE OF THE SOURCE CODE.",
}

export const ACCESS_TOKEN_EXPIRE_IN = "1d"
export const REFRESH_TOKEN_EXPIRE_IN = "7d"
